### PR TITLE
Change PackageInfo.g URLs to point at GitHub

### PR DESCRIPTION
**Pull request by fingolfin**
Also rename gpl.txt -> LICENSE.

This PR only makes senes if a `gh-pages` branch is set up to enable the new URLs. This is described at length on <https://github.com/gap-system/GitHubPagesForGAP>. Alternatively, I can do it for you, it'll take me about 40 seconds to do.

It would be great if there was a release of the DESIGN package soon, too. It is now the second-oldest distributed package in terms of when its most recent release was; the only older package is repsn, and I just made a release of that.

I realize not that much has changed in DESIGN itself, but already the added tests and the new `License` field in the `PackageInfo.g`, plus the issue tracker URL, make it desirable for the GAP team to see this released as 1.6.1 or 1.7. I am sure @alex-konovalov will agree.

Thank you, and let me know if I can be of any assistance with this. (I think we'll meet in a few weeks in Halle, too).

### CODE REVIEW

**Comment by lhsoicher** [comment]
Hi Max,

> This PR only makes senes if a gh-pages branch is set up to enable the new URLs. This is described at length on
> https://github.com/gap-system/GitHubPagesForGAP. Alternatively, I can do it for you,
> it'll take me about 40 seconds to do.

Yes, please do this for me. Thanks.

> It would be great if there was a release of the DESIGN package soon, too. ...

> Thank you, and let me know if I can be of any assistance with this. (I think we'll meet in a few weeks in Halle, too).

My plan is to have new versions of both DESIGN and GRAPE ready for release just before or during
GAP Days in Halle, where your help and advice will be much appreciated.

Presumably, similar file changes should be made in GRAPE?

Thanks,
Leonard

________________________________________

**Comment by fingolfin** [comment]
Done, result see https://gap-packages.github.io/design/ resp. the `gh-pages` branch.

There is nothing to be done for GRAPE, as we already performed all these steps there.

**Comment by lhsoicher** [comment]
> Done, result see https://gap-packages.github.io/design/ resp. the gh-pages branch.

Thank you.

> There is nothing to be done for GRAPE, as we already performed all these steps there.

I meant, in GRAPE, should I rename gpl.txt to LICENSE, README to README.md, move the version
changes into a new file new CHANGES.md, and change PackageInfo.g by updating the README_URL
to reflect the change in the readme file name?  And what about the file COPYING?

________________________________________

**Comment by fingolfin** [comment]
Ahh, sorry, I misunderstood. Well, I'd appreciate such changes, but they are not a strict necessity either.

Note that renaming README to README.md only makes sense if the file content really is (changed to) Markdown.

**Comment by lhsoicher** [comment]
Hi Max,

> Ahh, sorry, I misunderstood. Well, I'd appreciate such changes, but they are not a strict necessity either.

> Note that renaming README to README.md only makes sense if the file content really is (changed to) Markdown.

I plan to do this, finish off new versions of both GRAPE and DESIGN, and release these new versions during the
GAP Days workshop next week. I look forward to seeing you there, and will likely need some of your expert 
help and advice!

Leonard

**Pull request merged**
